name: Release JS package @teamhanko/passkeys-sdk

on:
  push:
    tags:
      - "@teamhanko/passkeys-sdk@*"

defaults:
  run:
    working-directory: packages/js/passkeys-sdk

permissions:
  id-token: write  # Required for OIDC

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24.11.1'
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - run: bun run build
      - name: publish passkeys-sdk
        run: npm publish --access=public